baseURL = "http://suryatresna.asia/"
languageCode = "en-us"
title = "Surya Tresna"
theme = "storie"
[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "About"
  weight = 3
  identifier = "about"
  url = "/about"
  
  
[params]
  author = "Surya Tresna Agung"
  avatar = "https://res.cloudinary.com/suryatresna/image/upload/r_0/v1514573058/profile_new_ftl8lr.jpg"
  contact = "mailto:surya.tresna@gmail.com"
  bio = "Freelance Web Programmer and Web Technology Enthusiast"
  logo = "https://res.cloudinary.com/suryatresna/image/upload/v1514024457/logo_xsvxgd.png"
  facebook = "suryatresna"
  github = "suryatresna"
  linkedin = "surya-tresna-agung-2ab03683"
  instagram = "surya.tresna"
