baseURL = "http://suryatresna.asia/"
languageCode = "en-us"
title = "Surya Tresna"
theme = "storie"
[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "About"
  weight = 3
  identifier = "about"
  url = "/about"
  
  
[params]
  logo = "https://res.cloudinary.com/suryatresna/image/upload/v1514024457/logo_xsvxgd.png"
